export const PIXEL = 1;

export const PAL = {
  red: '#C04040', skin: '#F8B050', blue: '#4040F8', brown: '#804000',
  white: '#F8F8F8', black: '#000000', yellow: '#F8D050', green: '#40A040',
  goombaBr: '#A05020', goombaDk: '#682800',
  brick: '#C06040', brickDk: '#803020', brickLn: '#E09070',
  quest: '#F8D050', questDk: '#C08020', used: '#804040',
  pipeGn: '#40C040', pipeDk: '#208020', pipeLt: '#80E880',
  groundT: '#E8C080', groundF: '#C08040', sky: '#5C94FC',
  mushRd: '#F04040', mushWt: '#F8F8F8',
  starYl: '#F8F800', starOr: '#F8A000',
  flowerR: '#F84040', flowerW: '#F8F8F8',
  flag: '#40C040', flagPl: '#A0A0A0',
  castle: '#A08060', castleD: '#604020',
  cloud: '#F8F8F8', hillGn: '#68C8A0', bushGn: '#40A040',
  hatRd: '#D84848', hatDk: '#A02828', shrt: '#E85050', shrtDk: '#B83838',
  ovrl: '#3850E8', ovrlDk: '#2838B0', shoe: '#683010', shoeDk: '#401808',
  hair: '#5C3010', glove: '#F8F8F8',
  koLt: '#58D058', koDk: '#289028', koYl: '#E8C040', koSh: '#1A6018',
  pipeM: '#60D860', mushSp: '#D03030',
};

// Each cell = one screen pixel. Right-facing only; Canvas flips for left.

const HEAD = [
  '........RRRRRRRR........',
  '.......RRRRRRRRRR.......',
  '......RRRRRRRRRRRR......',
  '.....RRRRrrRRrrRRRR.....',
  '.....RRrrHHHHHHrrRR.....',
  '....HHHsssssssssHHH.....',
  '....sssssssssssssss.....',
  '....ssWWssKKssWWss.....',
  '....ssKKKKKKKKssss.....',
  '....sssssssssssss.......',
  '....ssWWWWWWWWssss......',
  '...ssBBBBBBBBBBBBss.....',
  '...ssBBBYYBBBYYBBss.....',
  '...ssBBB....ssBBBss.....',
  '....ssBBB..ssBBBss......',
  '....ssBBBBBBBBBBss......',
  '.....ssBBBBBBBBss.......',
  '......ssBBBBBBss........',
];

const LEGS_WALK = [
  '....ssBBBBBBBBBBBBss....',
  '....ssBBB......BBBss....',
  '....ssBBB......BBBss....',
  '....ssNNN......NNNss....',
  '...ssNNNN......NNNNss...',
  '...ssNNNN......NNNNss...',
  '....ssNN........NNss....',
  '.....ss..........ss.....',
  '........................',
  '........................',
  '........................',
  '........................',
];

const LEGS_WALK2 = [
  '....ssBBBBBBBBBBBBss....',
  '...ssBBB........BBBss...',
  '....BBB..........BBB....',
  '....BBB..........NNN....',
  '...NNNN..........NNNN...',
  '...NNNN..........NNNN...',
  '....NN............NN....',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
];

const LEGS_JUMP = [
  '.ssBBB......ssBBBss.....',
  'ssBBB........BBBBss.....',
  'ssBBB........BBBBss.....',
  '.ssBBBBBBBBBBBBBBss.....',
  '..ssBBBBBBBBBBBBss......',
  '..ssBBB......BBBss......',
  '..NNN........NNNss......',
  '.NNNN........NNNN.......',
  '.NNNN........NNNN.......',
  '..NN..........NN........',
  '........................',
  '........................',
];

const TORSO_BIG = [
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
  '....ssBBBBBBBBBBss......',
];

const LEGS_BIG_WALK = [
  '....ssBBBBBBBBBBBBss....',
  '....ssBBBBBBBBBBBBss....',
  '....ssBBB......BBBss....',
  '....ssBBB......BBBss....',
  '....ssNNN......NNNss....',
  '...ssNNNN......NNNNss...',
  '...ssNNNN......NNNNss...',
  '....ssNN........NNss....',
  '.....ss..........ss.....',
  '........................',
  '........................',
  '........................',
];

const LEGS_BIG_WALK2 = [
  '....ssBBBBBBBBBBBBss....',
  '....ssBBBBBBBBBBBBss....',
  '...ssBBB........BBBss...',
  '....BBB..........BBB....',
  '....BBB..........NNN....',
  '...NNNN..........NNNN...',
  '...NNNN..........NNNN...',
  '....NN............NN....',
  '........................',
  '........................',
  '........................',
  '........................',
];

const LEGS_BIG_JUMP = [
  '.ssBBB......ssBBBss.....',
  'ssBBB........BBBBss.....',
  'ssBBB........BBBBss.....',
  '.ssBBBBBBBBBBBBBBss.....',
  '..ssBBBBBBBBBBBBss......',
  '..ssBBBBBBBBBBBBss......',
  '..ssBBB......BBBss......',
  '..NNN........NNNss......',
  '.NNNN........NNNN.......',
  '.NNNN........NNNN.......',
  '..NN..........NN........',
  '........................',
];

function join(...parts) { return parts.flat(); }

function padRows(rows) {
  const w = Math.max(...rows.map(r => r.length));
  return rows.map(r => r.padEnd(w, '.'));
}

function norm(obj) {
  const out = {};
  for (const [k, v] of Object.entries(obj)) out[k] = padRows(v);
  return out;
}

const RAW = {
  mSmall: join(HEAD, LEGS_WALK),
  mSmall2: join(HEAD, LEGS_WALK2),
  mJump: join(HEAD.slice(0, 14), LEGS_JUMP, Array(4).fill('........................')),
  mBig: join(HEAD, TORSO_BIG, LEGS_BIG_WALK),
  mBig2: join(HEAD, TORSO_BIG, LEGS_BIG_WALK2),
  mBigJump: join(HEAD, TORSO_BIG, LEGS_BIG_JUMP),
  goomba: [
    '...........AAAAA...........',
    '.........AAAAAAAAA.........',
    '........AA.AAAAA.AA........',
    '.......AAA.K...K.AAA.......',
    '......AAAA.KKKKK.AAAA......',
    '......AAAA..K.K..AAAA......',
    '......AA..WWWWWWW..AA......',
    '......AA..WK...KW..AA......',
    '......AA..WWWWWWW..AA......',
    '......AAAA..K.K..AAAA......',
    '.......AAA.AAAAA.AAA.......',
    '........AAAAAAAAAAA........',
    '.......AAADDDDDDDAA........',
    '......AAAA..DDD..AAAA......',
    '.....DDDDD....DDDDDD.......',
    '.....DDDDD....DDDDDD.......',
    '...........................',
    '...........................',
    '...........................',
    '...........................',
    '...........................',
    '...........................',
    '...........................',
    '...........................',
    '...........................',
    '...........................',
    '...........................',
    '...........................',
  ],
  goomba2: [
    '...........AAAAA...........',
    '.........AAAAAAAAA.........',
    '........AA.AAAAA.AA........',
    '.......AAA.K...K.AAA.......',
    '......AAAA.KKKKK.AAAA......',
    '......AAAA..K.K..AAAA......',
    '......AA..WWWWWWW..AA......',
    '......AA..WK...KW..AA......',
    '......AA..WWWWWWW..AA......',
    '......AAAA..K.K..AAAA......',
    '.......AAA.AAAAA.AAA.......',
    '........AAAAAAAAAAA........',
    '.......AAAAADDDDDAA........',
    '......DDDDDD.DDDDDDD.......',
    '.....DDDDD......DDDDD......',
    '.....DDDDD......DDDDD......',
    '...........................',
    '...........................',
    '...........................',
    '...........................',
    '...........................',
    '...........................',
    '...........................',
    '...........................',
    '...........................',
    '...........................',
    '...........................',
    '...........................',
  ],
  koopa: [
    '..........EEEEEE..........',
    '.........EEEEEEEE.........',
    '........EEEEEEEEEE........',
    '.......EEEEEEEEEEEE.......',
    '.......EEE....EE.EEE......',
    '.......EEEEEEEEEEEE.......',
    '........EEEEEEEEEE........',
    '........0000000000........',
    '.......000000000000.......',
    '......00000000000000......',
    '......00....0000....00....',
    '.....EEEEEEEEEEEEEEEE.....',
    '....EEEEEEEEEEEEEEEEEE....',
    '...EEEEEEEEEEEEEEEEEEEE...',
    '...EEE..EEEEEEEE..EEEE....',
    '....EEE.EEEEEEEE.EEE......',
    '....EEE.EEEEEEEE.EEE......',
    '....EEE.EEEEEEEE.EEE......',
    '....EEE....EE....EEE......',
    '.....EE..........EE.......',
    '......E..........E........',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
  ],
  koopa2: [
    '..........EEEEEE..........',
    '.........EEEEEEEE.........',
    '........EEEEEEEEEE........',
    '.......EEEEEEEEEEEE.......',
    '.......EEE....EE.EEE......',
    '.......EEEEEEEEEEEE.......',
    '........EEEEEEEEEE........',
    '........0000000000........',
    '.......000000000000.......',
    '......00000000000000......',
    '......00....0000....00....',
    '.....EEEEEEEEEEEEEEEE.....',
    '....EEEEEEEEEEEEEEEEEE....',
    '...EEEEEEEEEEEEEEEEEEEE...',
    '...EEE..EEEEEEEE..EEEE....',
    '....EEE.EEEEEEEE.EEE......',
    '....EEE.EEEEEEEE.EEE......',
    '....EEE.EEEEEEEE.EEE......',
    '....EEE....EE....EEE......',
    '.....EE..........EE.......',
    '......EE........EE........',
    '.......E........E.........',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
  ],
  mushroom: [
    '......22222222......',
    '....222222222222....',
    '...22222222222222...',
    '..2222.MMMMMM.2222..',
    '..222.MMMMMMMM.222..',
    '.2222.MMM..MMM.2222.',
    '.222.MMMMMMMM.MMM22.',
    '.222.MMM..MMM.MMM22.',
    '..222.MMMMMMMM.222..',
    '..2222.MMMMMM.2222..',
    '...22222222222222...',
    '....22......22......',
    '....22.MMMM.22......',
    '....22.MMMM.22......',
    '.....22....22.......',
    '.....22....22.......',
    '....................',
    '....................',
  ],
  fireflower: [
    '.......2222222.......',
    '......222222222......',
    '.....22222222222.....',
    '.....22..WWWW..22....',
    '....222..WWWW..222...',
    '....22222222222222...',
    '....22222222222222...',
    '.....222222222222....',
    '....22...3333...22...',
    '...222...3333...222..',
    '...222222222222222...',
    '...222........2222...',
    '....22........22.....',
    '.....2..........2....',
    '....................',
    '....................',
  ],
  star: [
    '.......OOO.......',
    '......OOOOO......',
    '.....OOYYYOO.....',
    '....OOOYYYOOO....',
    '...OOOOYYYYOOO...',
    '..OOOOOYYOOOOOO..',
    '.OOOOOYYYYOOOOOO.',
    'OOOOOYYYYYYOOOOOO',
    '.OOOOOYYYYOOOOOO.',
    '..OOOOOYYOOOOOO..',
    '...OOOOYYYYOOO...',
    '....OOOYYYOOO....',
    '.....OOYYYOO.....',
    '......OOOOO......',
    '.......OOO.......',
    '................',
  ],
  qblock: [
    '..QQQQQQQQQQQQQQQQQQQQQQ..',
    '.QQQQQQQQQQQQQQQQQQQQQQQQ.',
    '.QQIIIIIIIIIIIIIIIIIIQQQQ.',
    '.QQIQQQQQQQQQQQQQQQQIQQQQ.',
    '.QQIQQIIIIIIIIIIQQQQIQQQQ.',
    '.QQIQQIQQQQQQQQIQQQQIQQQQ.',
    '.QQIQQIQQQQQQQQIQQQQIQQQQ.',
    '.QQIQQIQQQQQQQQIQQQQIQQQQ.',
    '.QQIQQIQQQQQQQQIQQQQIQQQQ.',
    '.QQIQQIQQQQQQQQIQQQQIQQQQ.',
    '.QQIQQIQQQQQQQQIQQQQIQQQQ.',
    '.QQIQQIQQQQQQQQIQQQQIQQQQ.',
    '.QQIQQIQQQQQQQQIQQQQIQQQQ.',
    '.QQIQQIQQQQQQQQIQQQQIQQQQ.',
    '.QQIQQIIIIIIIIIIQQQQIQQQQ.',
    '.QQIQQQQQQQQQQQQQQQQIQQQQ.',
    '.QQIIIIIIIIIIIIIIIIIIQQQQ.',
    '.QQQQQQQQQQQQQQQQQQQQQQQQ.',
    '.QQQQQQQQQQQQQQQQQQQQQQQQ.',
    '..QQQQQQQQQQQQQQQQQQQQQQ..',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
  ],
  used: [
    '..UUUUUUUUUUUUUUUUUUUUUU..',
    '.UUUUUUUUUUUUUUUUUUUUUUUU.',
    '.UUIIIIIIIIIIIIIIIIIIIUUU.',
    '.UUIUUUUUUUUUUUUUUUUUUQUU.',
    '.UUIUUUUUUUUUUUUUUUUUUQUU.',
    '.UUIUUUUUUUUUUUUUUUUUUQUU.',
    '.UUIUUUUUUUUUUUUUUUUUUQUU.',
    '.UUIUUUUUUUUUUUUUUUUUUQUU.',
    '.UUIUUUUUUUUUUUUUUUUUUQUU.',
    '.UUIUUUUUUUUUUUUUUUUUUQUU.',
    '.UUIUUUUUUUUUUUUUUUUUUQUU.',
    '.UUIUUUUUUUUUUUUUUUUUUQUU.',
    '.UUIUUUUUUUUUUUUUUUUUUQUU.',
    '.UUIUUUUUUUUUUUUUUUUUUQUU.',
    '.UUIIIIIIIIIIIIIIIIIIIUUU.',
    '.UUUUUUUUUUUUUUUUUUUUUUUU.',
    '.UUUUUUUUUUUUUUUUUUUUUUUU.',
    '..UUUUUUUUUUUUUUUUUUUUUU..',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
  ],
  brick: [
    '..BBJJBBJJBBJJBBJJBBJJBBJJ..',
    '.BJJBBJJBBJJBBJJBBJJBBJJBBJ.',
    'BBJJBBJJBBJJBBJJBBJJBBJJBBJJ',
    'BBVVBBJJBBJJBBJJBBJJBBJJBBJJ',
    'BBBBBBVVBBBBBBBBVVBBBBBBBBBB',
    '.BBBBBBBBBBBBBBBBBBBBBBBBBB.',
    '..BBJJBBJJBBJJBBJJBBJJBBJJ..',
    '.BJJBBJJBBJJBBJJBBJJBBJJBBJ.',
    'BBJJBBJJBBJJBBJJBBJJBBJJBBJJ',
    'BBVVBBJJBBJJBBJJBBJJBBJJBBJJ',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    '.BBBBBBBBBB....BBBBBBBBBBBB.',
    '..BBJJBBJJBBJJBBJJBBJJBBJJ..',
    '.BJJBBJJBBJJBBJJBBJJBBJJBBJ.',
    'BBJJBBJJBBJJBBJJBBJJBBJJBBJJ',
    'BBVVBBJJBBJJBBJJBBJJBBJJBBJJ',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    '.BBBBBBBBBBBBBBBBBBBBBBBBBB.',
    '..BBJJBBJJBBJJBBJJBBJJBBJJ..',
    '.BJJBBJJBBJJBBJJBBJJBBJJBBJ.',
    'BBJJBBJJBBJJBBJJBBJJBBJJBBJJ',
    'BBVVBBJJBBJJBBJJBBJJBBJJBBJJ',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    '.BBBBBBBBBBBBBBBBBBBBBBBBBB.',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
  ],
  castle: [
    '..CCCCCCCCCCCCCCCCCCCCCCCC..',
    '.CCCCCCCCCCCCCCCCCCCCCCCCCC.',
    'CCCCCCCCCCCCCCCCCCCCCCCCCCCC',
    'CCX..CCCCCCCCCCCCCCCC..XCCCC',
    'CCX..CCCCCCCCCCCCCCCC..XCCCC',
    'CCCCCCCCCCCCCCCCCCCCCCCCCCCC',
    'CCCCCCCCCCCCCCCCCCCCCCCCCCCC',
    'CCCCCCCCCCCCCCCCCCCCCCCCCCCC',
    'CCX..CCCCCCCCCCCCCCCC..XCCCC',
    'CCX..CCCCCCCCCCCCCCCC..XCCCC',
    'CCCCCCCCCCCCCCCCCCCCCCCCCCCC',
    'CCX..CCCCCCCCCCCCCCCC..XCCCC',
    'CCX..CCCCCCCCCCCCCCCC..XCCCC',
    'CCCC....CCCCCCCC....CCCCCCCC',
    '.CCCC......CCCC......CCCCCC.',
    '..CCCCCCCCCCCCCCCCCCCCCCCC..',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
    '..........................',
  ],
};

export const SPR_MARKO = norm(RAW);

export const SPR_PAL = {
  R: PAL.hatRd, r: PAL.hatDk,
  S: PAL.skin, s: PAL.shrtDk,
  B: PAL.ovrl, b: PAL.ovrlDk,
  N: PAL.shoe, n: PAL.shoeDk,
  W: PAL.white, K: PAL.black,
  Y: PAL.yellow, G: PAL.goombaBr, D: PAL.goombaDk,
  H: PAL.hair, E: PAL.koLt, F: PAL.koDk,
  M: PAL.mushWt, O: PAL.starOr, Q: PAL.quest,
  I: PAL.questDk, J: PAL.brickLn, V: PAL.brickDk,
  U: PAL.used, C: PAL.castle, X: PAL.castleD,
  A: PAL.goombaBr, '0': PAL.koYl,
  '2': PAL.mushRd, '3': PAL.green,
  '.': null, ' ': null,
};
